apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 4499 # Container port
      nodePort: 30007  # NodePort (must be in range 30000–32767)

