name: CI/CD - Build and Deploy
on:
push:
branches: [ main ]


permissions:
contents: read
packages: write
id-token: write


jobs:
build-and-push:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up QEMU
uses: docker/setup-qemu-action@v3


- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v3


- name: Log in to GitHub Container Registry
uses: docker/login-action@v3
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GHCR_PAT }}


- name: Build and push image
uses: docker/build-push-action@v5
with:
context: .
push: true
tags: |
ghcr.io/${{ github.repository_owner }}/wisecow:latest
ghcr.io/${{ github.repository_owner }}/wisecow:${{ github.sha }}


deploy-to-k8s:
name: Deploy to Kubernetes (optional)
runs-on: ubuntu-latest
needs: build-and-push
if: ${{ secrets.KUBE_CONFIG_DATA != '' }}
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Setup kubectl
uses: azure/setup-kubectl@v3


- name: Decode KUBECONFIG
run: |
echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig
export KUBECONFIG=$PWD/kubeconfig
env:
KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}


- name: Update deployment image
run: |
kubectl --kubeconfig=kubeconfig -n wisecow set image deployment/wisecow-deployment wisecow=ghcr.io/${{ github.repository_owner }}/wisecow:latest --record
